### ISSUE TITLE
Preprocessing issue

### ISSUE THREAD

**Issue by franzt7788** [NEXGEM/TRIPLEX#5]
Hi there,

Thank you for sharing this nice work! I met a problem when I ran the python extract_features.py for neighboring feature:
Traceback (most recent call last):
  File "/home/franzt/tri/triplex/preprocess/extract_features.py", line 98, in <module>
    features = get_sub_features(model, patches, num_n)

  File "/home/franzt/tri/triplex/preprocess/extract_features.py", line 28, in get_sub_features
    features = model(patch.to(torch.device('cuda:0')))
RuntimeError: Calculated padded input size per channel: (230 x 6). Kernel size: (7 x 7). Kernel size can't be greater than actual input size

It happened at all three internal dataset, do you know what happens? Thank you.

Best,
Franzt

**Comment by ymoneych** [comment]
Hi, we appreciate your interest in our research, and sorry for the delay in responding. 

We've noticed some bugs in our preprocessing code and have just fixed them.
The bug you mention may not be directly related, but I was wondering if you could try running the code again?

I've run the extract_features.py code now, but it doesn't reproduce the bug you mentioned, so if you see it again, it would be great to know the following:

1. Whether you used the data we provided
3. What options you used when you ran extract_features.py.

Best,
Youngmin Chung

**Comment by franzt7788** [comment]
Hi Youngmin,

Thank you for your paitent for my issue. I use your updated code for preprocessing your data, and it works. Thanks!

Best,
Franzt

**Comment by franzt7788** [comment]
Hi Youngmin,

I met another problem. May I ask how to extract the feature of 10x_breast_ff1? I got error information when I try to extract the feature of 10x_breast_ff1: 

Traceback (most recent call last):
  File "/home/franzt/tri/triplex/preprocess/extract_features.py", line 144, in <module>
    for i, patches in tqdm(enumerate(dataloader)):
  File "/opt/anaconda3/envs/tri/lib/python3.12/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/opt/anaconda3/envs/tri/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/tri/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/opt/anaconda3/envs/tri/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/opt/anaconda3/envs/tri/lib/python3.12/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/anaconda3/envs/tri/lib/python3.12/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/opt/anaconda3/envs/tri/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]

  File "/home/franzt/tri/triplex/datasets/st_data.py", line 356, in __getitem__
    patches[j] = patch
RuntimeError: The expanded size of the tensor (224) must match the existing size (187) at non-singleton dimension 1.  Target sizes: [3, 224, 224].  Tensor sizes: [3, 187, 224]

When I tired 10x_breast_ff2 or 10x_breast_ff3, it is working. Do you know what happens? Thank you.

Best,
Franzt
